<?php

namespace Container3XbKyYd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryTypeService extends App_KernelAmperDebugContainer
{
    /**
     * Gets the private 'App\Form\CategoryType' shared autowired service.
     *
     * @return \App\Form\CategoryType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CategoryType.php';

        return $container->privates['App\\Form\\CategoryType'] = new \App\Form\CategoryType();
    }
}
