#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Command\DatabaseSetupCommand;
use App\Command\CreateUserCommand;
use Doctrine\ORM\EntityManager;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher;
use Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactory;

$app = new Application();
$app->add(new DatabaseSetupCommand());
//$app->add(new CreateUserCommand(new EntityManager(null, null), new UserPasswordHasher(new PasswordHasherFactory([]))));
$app->run();