<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3XbKyYd\App_KernelAmperDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3XbKyYd/App_KernelAmperDebugContainer.php') {
    touch(__DIR__.'/Container3XbKyYd.legacy');

    return;
}

if (!\class_exists(App_KernelAmperDebugContainer::class, false)) {
    \class_alias(\Container3XbKyYd\App_KernelAmperDebugContainer::class, App_KernelAmperDebugContainer::class, false);
}

return new \Container3XbKyYd\App_KernelAmperDebugContainer([
    'container.build_hash' => '3XbKyYd',
    'container.build_id' => '6242b7ce',
    'container.build_time' => 1665424050,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3XbKyYd');
