<?php

namespace ContainerH16zYqO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabaseSetupCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DatabaseSetupCommand' shared autowired service.
     *
     * @return \App\Command\DatabaseSetupCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/DatabaseSetupCommand.php';

        $container->privates['App\\Command\\DatabaseSetupCommand'] = $instance = new \App\Command\DatabaseSetupCommand();

        $instance->setName('db:setup');
        $instance->setDescription('Set up your database.');

        return $instance;
    }
}
