<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU6ZhxSx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU6ZhxSx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU6ZhxSx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU6ZhxSx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU6ZhxSx\App_KernelDevDebugContainer([
    'container.build_hash' => 'U6ZhxSx',
    'container.build_id' => 'bbed2c30',
    'container.build_time' => 1665263238,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU6ZhxSx');
