<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH16zYqO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH16zYqO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH16zYqO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH16zYqO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH16zYqO\App_KernelDevDebugContainer([
    'container.build_hash' => 'H16zYqO',
    'container.build_id' => 'e57e2fa2',
    'container.build_time' => 1665332032,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH16zYqO');
